apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ print .Values.APP_NAME "-" .Values.NAMESPACE "-utils-identity" }}
  namespace: {{ .Values.NAMESPACE }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.ARM_WORKLOAD_APP_ID }}
    azure.workload.identity/tenant-id: {{ .Values.ARM_TENANT_ID }}
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utils
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: utils
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ print .Values.APP_NAME "-" .Values.NAMESPACE "-utils-identity" }}
      containers:
      - name: utils
        image:  {{ print .Values.DOCKER_REPO ":" .Values.COMMIT_VERSION }} 
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "128Mi"
            cpu: "0.5"
